# Generated by Django 6.0.4 on 2026-04-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='craeted_on',
            new_name='created_on',
        ),
    ]
