# Generated by Django 6.0 on 2026-01-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=4),
        ),
    ]
