# Generated by Django 6.0.3 on 2026-04-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=1000)),
                ('previous_work', models.TextField(max_length=500)),
                ('skills', models.CharField(max_length=200)),
            ],
        ),
    ]
